// <auto-generated />
namespace PlayoffsCreator.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TeamNamememberaddedtoPlayerModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TeamNamememberaddedtoPlayerModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201507191640474_TeamName member added to PlayerModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
