// <auto-generated />
namespace PlayoffsCreator.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class dodaniegamecontexstu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dodaniegamecontexstu));
        
        string IMigrationMetadata.Id
        {
            get { return "201507201447171_dodanie gamecontexstu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
