// <auto-generated />
namespace PlayoffsCreator.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class roundmodeladded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(roundmodeladded));
        
        string IMigrationMetadata.Id
        {
            get { return "201507151510311_round model added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
